name: Build, Push, and Deploy Docker Images to VPS

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: hoangnguyen2003
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./personal-hub-backend
        file: ./personal-hub-backend/Dockerfile
        push: true
        tags: hoangnguyen2003/personal-hub-backend:latest

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./personal-hub-frontend
        file: ./personal-hub-frontend/Dockerfile
        push: true
        tags: hoangnguyen2003/personal-hub-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Copy docker-compose.yml to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-compose.yml"
        target: "/home/${{ secrets.SSH_USER }}/personal-hub"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export DOCKER_HUB_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}
          docker login -u hoangnguyen2003 -p $DOCKER_HUB_TOKEN
          cd /home/${{ secrets.SSH_USER }}/personal-hub
          docker-compose pull
          docker-compose up -d